#pragma once

#include "..//common.h"

enum JSH_TOPOLOGY {

	JSH_TOPOLOGY_TRIANGLES,
	JSH_TOPOLOGY_TRIANGLE_STRIP,
	JSH_TOPOLOGY_LINES,
	JSH_TOPOLOGY_LINE_STRIP,
	JSH_TOPOLOGY_POINTS

};

enum JSH_USAGE {
	JSH_USAGE_DEFAULT = 0,
	JSH_USAGE_IMMUTABLE = 1,
	JSH_USAGE_DYNAMIC = 2,
	JSH_USAGE_STAGING = 3
};

enum JSH_BIND_FLAG {
	JSH_BIND_VERTEX_BUFFER = 0x1L,
	JSH_BIND_INDEX_BUFFER = 0x2L,
	JSH_BIND_CONSTANT_BUFFER = 0x4L,
	JSH_BIND_SHADER_RESOURCE = 0x8L,
	JSH_BIND_STREAM_OUTPUT = 0x10L,
	JSH_BIND_RENDER_TARGET = 0x20L,
	JSH_BIND_DEPTH_STENCIL = 0x40L,
	JSH_BIND_UNORDERED_ACCESS = 0x80L,
	JSH_BIND_DECODER = 0x200L,
	JSH_BIND_VIDEO_ENCODER = 0x400L
};

struct JSH_BUFFER_DESC {
	uint32 ByteWidth;
	JSH_USAGE Usage;
	uint32 BindFlags;
	uint32 CPUAccessFlags;
	uint32 MiscFlags;
	uint32 StructureByteStride;
};

struct JSH_SUBRESOURCE_DATA {
	const void* pSysMem;
	uint32 SysMemPitch;
	uint32 SysMemSlicePitch;
};