#pragma once

#include "Math.h"

#define JSH_DEBUG
#define JSH_IMGUI
#define JSH_CONSOLE
#define JSH_PLATFORM_WINDOWS

#define JSH_ECS_MAX_COMPONENTS_TYPES 64
#define JSH_ECS_NAMECOMPONENT_SIZE 32

#define JSH_GFX_SPRITE_BATCH_COUNT 10000u